import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Button, Input, Select, Spinner, Switch } from '@fluentui/react-components';
import type { OpportunityDetail, PublicSignal, SignalResponse } from '../../../packages/contracts/src/portfolio';
import { getOpportunity, getSignals } from './api';
import './styles.css';

function App() {
  const [subscriber, setSubscriber] = useState(false);
  const [query, setQuery] = useState(() => new URLSearchParams(location.search));
  const [search, setSearch] = useState(query.get('q') ?? '');
  const [response, setResponse] = useState<SignalResponse>();
  const [selected, setSelected] = useState<PublicSignal>();
  const [opportunity, setOpportunity] = useState<OpportunityDetail>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { setLoading(true); getSignals(query).then(setResponse).catch(e => setError(e.message)).finally(() => setLoading(false)); const next = query.toString(); history.replaceState(null, '', next ? `?${next}` : location.pathname); }, [query]);
  const update = (key: string, value: string) => { const next = new URLSearchParams(query); value ? next.set(key, value) : next.delete(key); setQuery(next); };
  const selectSignal = async (signal: PublicSignal) => { setSelected(signal); setOpportunity(undefined); setError(''); try { setOpportunity(await getOpportunity(signal.id, subscriber)); } catch (e) { setError((e as Error).message); } };
  return <div className="shell">
    <header className="topbar"><div className="brand"><span className="mark">O</span><strong>AccountSignal AI</strong></div><nav><a className="active">FSI Intelligence</a><a>Accounts</a><a>Research</a><a>About</a></nav><div className="top-actions"><span>Subscriber sign in</span><Button appearance="primary">Request private access</Button></div></header>
    <section className="hero"><div><p className="eyebrow">PUBLIC FSI INTELLIGENCE</p><h1>Financial Services Signals and Growth Themes</h1><p>Track business, technology and platform changes across banking, payments, wealth, retirement and insurance.</p><p>Opportunity intelligence and pursuit guidance are available to subscribers.</p></div><div className="updated"><strong>Updated Sep 26</strong><span>12 signals in this prototype</span><span>4 opportunity classifications changed</span></div></section>
    <section className="toolbar"><Input value={search} onChange={(_, data) => { setSearch(data.value); update('q', data.value); }} placeholder="Search institution, domain or technology" /><Select value={query.get('domain') ?? ''} onChange={(_, data) => update('domain', data.value)}><option value="">All FSI domains</option>{response?.facets.domains.map(item => <option key={item}>{item}</option>)}</Select><Select value={query.get('institution') ?? ''} onChange={(_, data) => update('institution', data.value)}><option value="">All institutions</option>{response?.facets.institutions.map(item => <option key={item.slug} value={item.slug}>{item.name}</option>)}</Select><Select value={query.get('since') ?? ''} onChange={(_, data) => update('since', data.value)}><option value="">All recency</option><option value="2026-09-01">Last 30 days</option><option value="2026-09-15">Last 14 days</option></Select><Switch checked={subscriber} onChange={(_, data) => setSubscriber(data.checked)} label={subscriber ? 'Demo subscriber' : 'Public mode'} /></section>
    <main className="content"><section className="feed"><div className="section-heading"><div><h2>Signals and domain themes</h2><p>Evidence-backed developments with implications for Financial Services growth teams</p></div><button className="link-button">Methodology</button></div><div className="chips"><button className={!query.get('domain') ? 'chip selected' : 'chip'} onClick={() => update('domain', '')}>All signals</button>{response?.facets.domains.map(item => <button key={item} className={query.get('domain') === item ? 'chip selected' : 'chip'} onClick={() => update('domain', item)}>{item}</button>)}</div>{loading ? <div className="state"><Spinner label="Loading signals" /></div> : error && !selected ? <div className="state error">{error}</div> : response?.items.length ? response.items.map(signal => <SignalCard key={signal.id} signal={signal} onSelect={() => selectSignal(signal)} />) : <div className="state">No signals match these filters. <Button onClick={() => setQuery(new URLSearchParams())}>Clear filters</Button></div>}<div className="subscriber-banner"><div><strong>Subscriber intelligence</strong><span>Full evidence, opportunity scope, buyer map, continuity and GTM guidance</span></div><Button appearance="primary">Explore private access</Button></div></section><aside className="rail">{selected ? <Detail signal={selected} opportunity={opportunity} subscriber={subscriber} error={error} /> : <><RailBlock title="Bank and institution news" items={['Merger planning advances across conversion workstreams','Efficiency program remains a management priority','Commercial platform investment continues']} /><RailBlock title="Industry developments" items={['Tokenization and real-time rails reshape payment architecture','Governed AI adoption moves toward production controls']} /><RailBlock title="Upcoming FSI events" items={['Commercial Banking and Payments Forum','Financial Services Data and AI Summit']} /></>}</aside></main><footer><span><b>PUBLIC ACCESS:</b> signals, sources, news, industry themes and events</span><span><b>SUBSCRIBER ACCESS:</b> opportunities, stakeholders, continuity and pursuit guidance</span></footer>
  </div>;
}
function SignalCard({ signal, onSelect }: { signal: PublicSignal; onSelect: () => void }) { return <article className="signal-card"><div className="institution"><strong>{signal.institution.name}</strong><span>{signal.institution.institutionType}</span></div><div className="signal-body"><span className="domain">{signal.domain}</span><h3>{signal.title}</h3><p>{signal.summary}</p><small><i /> {signal.evidence[0].sourceType} · Updated {signal.publishedAt.slice(5)}</small></div><div className="related"><small>RELATED OPPORTUNITY</small><button onClick={onSelect}>{signal.title.slice(0, 42)}...</button><span>▣ Subscriber intelligence</span></div></article>; }
function RailBlock({ title, items }: { title: string; items: string[] }) { return <section className="rail-block"><div className="rail-title"><h3>{title}</h3><button>View all</button></div>{items.map(item => <div className="rail-item" key={item}><small>ACCOUNT SIGNAL · SEP 25</small><strong>{item}</strong><span>AccountSignal view: evidence-backed context for growth teams.</span></div>)}</section>; }
function Detail({ signal, opportunity, subscriber, error }: { signal: PublicSignal; opportunity?: OpportunityDetail; subscriber: boolean; error: string }) { return <section className="detail"><div className="detail-top"><small>RELATED OPPORTUNITY</small><button>Close</button></div><h2>{opportunity?.title ?? signal.title}</h2>{opportunity ? <><span className="pill">{opportunity.classification}</span><p>{opportunity.executiveSummary}</p><h4>Business context</h4><ul>{opportunity.businessContext.map(item => <li key={item}>{item}</li>)}</ul><h4>Technology context</h4><ul>{opportunity.technologyContext.map(item => <li key={item}>{item}</li>)}</ul><div className="private-grid"><div><small>SALES READINESS</small><strong>{opportunity.salesReadiness}</strong></div><div><small>IMPLEMENTATION</small><strong>{opportunity.implementationWindow}</strong></div></div></> : <div className="gate"><strong>Subscriber intelligence is available for this signal.</strong><p>Unlock opportunity scope, buyer context and pursuit guidance in demo subscriber mode.</p>{!subscriber && <span>{error}</span>}</div>}</section>; }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
